# -*- coding: utf-8 -*-
"""
Created on Mon Aug 29 18:09:53 2022

@author: SHREE
"""

import networkx as nx
N =10
G= nx.grid_2d_graph(N,N)
import matplotlib.pyplot as plt
nx.draw(G)
plt.show()
# distorted graph generated by networkx
G.nodes()
#print(G)
pos = dict((n,n) for n in G.nodes())
#print(pos)
nx.draw(G,pos, with_labels = True)
plt.show()
# graph arranged in a grid like manner.